### PR TITLE
Validate

### PR DESCRIPTION
**Pull request by jrootham**
Add argument validation.

### CODE REVIEW

**Comment by rvagg** [comment]
yeah, I like this, I'll merge and bump major for this. But, can you rebase and squash to a single commit please?

**Comment by jrootham** [comment]
OK, but first I will have to figure out how to do that.  Is bumping major
absolutely required?  There should be no breaking changes (anything it
breaks should have broken anyway).

**Comment by rvagg** [comment]
`git rebase -i HEAD~7` (or maybe more than 7, depending on how the commit log is organised on your banch), then select squash for all but one of your own commits that you want to combine in to one. A good skill to have! I find myself using `git rebase -i` for a lot these days, not just squashing.

I'm thinking that bumping major is just a good precaution because the commandline may have changed for some who may be using it slightly wrong. Probably not absolutely required since it's not real breakage, I'm just in a precautionary mood and perhaps that'll change by the time I hit publish!

**Comment by rvagg** [comment]
closing due to age, feel free to open a new PR if you'd like to take another swing at this

**Pull request closed without merging**
