### PR TITLE
mod: removed the hard coded error message

### PR DESCRIPTION
**Pull request by MrJithil**
Removed the hard-coded error message and read them from Node Core.

### CODE REVIEW

**Comment by MrJithil** [comment]
Since no activities for a long period, tagging some collaborators below.
@isaacs @rvagg @pmuellr @medikoo

**Review by rvagg — APPROVED** [review]

**Comment by rvagg** [comment]
CI is unhappy here with `node` and a dependency, mind taking a look and figuring that out?

**Comment by rvagg** [comment]
maybe just rebase on current master (don't merge master in please) and we can get this merged and released

**Comment by MrJithil** [comment]
> maybe just rebase on current master (don't merge master in please) and we can get this merged and released

All good. Done rebasing. Please review.

**Pull request merged**
